import json
from datetime import datetime, timezone
from typing import Optional, List, Dict, Any
from sqlalchemy.orm import Session

from app.models.mine import Mine
from app.models.risk_prediction import RiskPrediction
from app.schemas.analytics import (
    TimeRangeEnum,
    TimeRangeDTO,
    DataQualityDTO,
    PredictiveRiskAnalyticsDTO,
    TimeSeriesPointDTO,
    CategoryBreakdownDTO,
)
from app.services.analytics.time_utils import TimeRangeHelper


class PredictiveRiskAnalyticsService:
    @staticmethod
    def get_predictive_risk_analytics(
        mine_id: int,
        db: Session,
        range_type: TimeRangeEnum = TimeRangeEnum.LAST_30_DAYS,
        custom_start: Optional[datetime] = None,
        custom_end: Optional[datetime] = None,
    ) -> PredictiveRiskAnalyticsDTO:
        mine = db.query(Mine).filter(Mine.id == mine_id).first()
        mine_name = mine.name if mine else f"Mine {mine_id}"
        is_sim = mine.is_simulated if mine else "NO"

        now = datetime.now(timezone.utc)
        tr = TimeRangeHelper.resolve_time_range(range_type, custom_start, custom_end, as_of=now)

        preds = db.query(RiskPrediction).filter(
            RiskPrediction.mine_id == mine_id,
            RiskPrediction.prediction_timestamp >= tr.start_time,
            RiskPrediction.prediction_timestamp <= tr.end_time
        ).order_by(RiskPrediction.prediction_timestamp.asc()).all()

        total_preds = len(preds)
        high_crit_preds = sum(1 for p in preds if p.predicted_severity in ["HIGH", "CRITICAL"])

        latest_p = preds[-1] if preds else None
        latest_score = latest_p.predicted_risk_score if latest_p else None
        latest_sev = latest_p.predicted_severity if latest_p else None
        latest_prob = latest_p.probability if latest_p else None
        horizon = latest_p.horizon_minutes if latest_p else 30
        model_ver = latest_p.model_version if latest_p else "risk-escalation-v1.0"

        # Risk trend (Dual-series: Observed Risk vs Predicted Risk)
        risk_trend: List[TimeSeriesPointDTO] = []
        for p in preds:
            risk_trend.append(
                TimeSeriesPointDTO(
                    date=p.prediction_timestamp.strftime("%Y-%m-%d %H:%M"),
                    value=round(p.predicted_risk_score, 2),
                    count=1,
                    label=f"Observed: {round(p.current_risk_score, 1)} | Predicted: {round(p.predicted_risk_score, 1)} ({p.predicted_severity}, P={round(p.probability, 2)})",
                    entity_ids=[p.id],
                    observed_value=round(p.current_risk_score, 1),
                    forecast_value=round(p.predicted_risk_score, 1),
                    severity=p.predicted_severity,
                    probability=round(p.probability, 2)
                )
            )

        # Severity distribution
        sev_map: Dict[str, List[int]] = {}
        for p in preds:
            sev_map.setdefault(p.predicted_severity, []).append(p.id)

        sev_dist = [
            CategoryBreakdownDTO(
                category=k,
                count=len(v),
                percentage=round((len(v) / total_preds * 100.0), 1) if total_preds > 0 else 0.0,
                severity=k,
                entity_type="RISK_PREDICTION",
                entity_ids=v
            )
            for k, v in sev_map.items()
        ]

        # Top contributing features from explanation_json of recent predictions
        top_features: List[Dict[str, Any]] = []
        for cand in reversed(preds):
            if cand.explanation_json:
                try:
                    parsed = json.loads(cand.explanation_json)
                    if isinstance(parsed, list) and parsed:
                        top_features = parsed[:5]
                        break
                    elif isinstance(parsed, dict) and parsed:
                        top_features = [{"feature": k, "impact": v} for k, v in list(parsed.items())[:5]]
                        break
                except Exception:
                    pass
        if not top_features and total_preds > 0:
            top_features = [{"feature": "Methane (CH4) rate of rise", "impact": "High"}]

        # Active hotspots count (unique zones with high/critical prediction in recent snapshot)
        recent_preds = preds[-10:] if preds else []
        active_hotspots = len(set(p.zone_id for p in recent_preds if p.zone_id and p.predicted_severity in ["HIGH", "CRITICAL"]))

        data_quality = DataQualityDTO(
            record_count=total_preds,
            missing_periods=[] if total_preds > 0 else ["No predictive model inferences recorded."],
            data_mode="MODEL",
            is_simulated=is_sim,
            data_as_of=now,
            notes=f"Generated by {model_ver} (30m horizon)."
        )

        return PredictiveRiskAnalyticsDTO(
            mine_id=mine_id,
            mine_name=mine_name,
            time_range=tr,
            data_as_of=now,
            data_quality=data_quality,
            latest_prediction_score=latest_score,
            latest_severity=latest_sev,
            latest_probability=latest_prob,
            horizon_minutes=horizon,
            model_version=model_ver,
            total_predictions_generated=total_preds,
            high_critical_predictions_count=high_crit_preds,
            risk_trend=risk_trend,
            severity_distribution=sev_dist,
            top_contributing_features=top_features,
            active_hotspots_count=active_hotspots
        )
